### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by mysyljr** [chrisveness/koa-sample-web-app-api-mysql#3]
Thanks for the awesome sample project. I'm considering to put the sample into product use. But I have not seen any transaction support. Can you provide any suggestion?

**Comment by chrisveness** [comment]
Can you clarify what you mean by transactions? Do you mean database (MySQL) transactions?

**Comment by mysyljr** [comment]
@chrisveness Yes, I mean mysql database transactions.

**Comment by chrisveness** [comment]
Transactions are supported by [mysql2](https://www.npmjs.com/package/mysql2) (as  documented in the [mysql](https://www.npmjs.com/package/mysql#transactions) library).

My (fairly simple) sample app has no compound operations which need to be linked together into a single transaction, hence no use of transactions.

An example of such use might be (assuming the database connection is held in [`ctx.state.db`](https://github.com/chrisveness/koa-sample-web-app-api-mysql/blob/574f4eee780e0bba48e8690eb38d5a9de15fdac7/app-admin/app-admin.js#L83)):

    try {
        await ctx.state.db.beginTransaction();
        await ctx.state.db.query('Insert Into Table1 Set FieldA = :value', { value: value1 });
        await ctx.state.db.query('Insert Into Table2 Set FieldB = :value', { value: value2 });
        await ctx.state.db.commit();
    } catch (e) {
        await ctx.state.db.rollback();
    }

**Comment by mysyljr** [comment]
Thank you for you explanation. But why don't us put the transaction support into a middleware? I googled for such middleware but didn't see any. Is this not recommended?

Another little problem is that my team complain that we can't see  the async stacktrace when error happens. Could you please give some suggestions about this?

**Comment by chrisveness** [comment]
Yes, you could put it in middleware – there would of course be a performance implication, but it may not be significant.

I think it would look something like this:

    app.use(async function transaction(ctx, next) {
        try {
            await ctx.state.db.beginTransaction();
            await next();
            await ctx.state.db.commit();
        catch (e) {
            await ctx.state.db.rollback();
            throw new Error('Transaction failed');
        }
    });

Of course, if any database queries had caught exceptions, you would have to re-throw them for the transaction to be correctly rolled back.

**Comment by chrisveness** [comment]
I haven't had any problems with seeing stacktraces – are you referring to seeing the stacktrace in the console, or to reporting it in web pages? Can you give any further details?

**Comment by mysyljr** [comment]
Thank you for the example.
I don't have problems with seeing stacktraces. I mean how to show asynchronous stacktraces. Do you know how to support this?

**Comment by chrisveness** [comment]
It's always said of async/await how much easier it makes error handling / exception management. If you can give me an example (which I would be able to replicate) of not seeing stacktraces I will look into it for you, otherwise I will close this.

**Comment by mysyljr** [comment]
Please don't close now. Sorry for my unclearness.

This is how to replicate my problem. 
For example, I make an error in app-admin/handlers/members.js. I change the sql from 'Select * From Member' to 'Select * From Member1'. 
Then if I visit http://admin.localhost:3000/members I will get an error.  Its stacktrace is like this:

Error: Table 'koa-sample-sandbox.member1' doesn't exist
      at Packet.asError (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/packets/packet.js:667:13)
      at Query.Command.execute (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/commands/command.js:29:22)
      at PoolConnection.Connection.handlePacket (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/connection.js:417:28)
      at PacketParser.onPacket (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/connection.js:93:16)
      at PacketParser.executeStart (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/packet_parser.js:73:14)
      at Socket.<anonymous> (/Users/Jerry/koa-sample-web-app-api-mysql/node_modules/mysql2/lib/connection.js:101:29)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:189:7)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)

The stacktrace contains no infomation about where the query is asyncly called. And we may want the stacktrace to mention something about app-admin/handlers/members.js.
Can you think of some method to solve this?

**Comment by mysyljr** [comment]
Can you take a look at this？

**Comment by chrisveness** [comment]
The author of the mysql2 library is looking into changing promise rejections in the library to use a local Error object which will provide stack calls referencing the calling site.

I'll keep you updated.

**Comment by mysyljr** [comment]
Thank you for your kindness.
But I just use the sql error as an example. If I do add a throw statement like this:
await ctx.render('members-list', { members }); throw(new Error('test'));

When I visit http://admin.localhost:3000/members, I get an error and the stacktrace is:
ReferenceError: bb is not defined
    at list (/Users/Jerry/koa-sample-web-app-api-mysql/app-admin/handlers/members.js:38:20)

No further stack information about where list is called. 
Can you think of any method to deal with this?

**Comment by chrisveness** [comment]
Apologies for the delay responding.

I cannot find any issue here.

I take it you are referring to line [34 of app-admin/handlers/members.js](https://github.com/chrisveness/koa-sample-web-app-api-mysql/blob/a9cc3e6/app-admin/handlers/members.js#L34). If I add `throw(new Error('test'));` to that line, I get a stack trace of

    Error: test
        at list (.../koa-sample-web-app-api-mysql/app-admin/handlers/members.js:34:65)

Which gives me the exact site of the error (the reference error you quote looks unrelated). I don't see what further information you require.

**Comment by mysyljr** [comment]
I mean when the program throw an error **after an await call**, I will get a stacktrace of only one sentence, no further. If a call b, b call c, and c throws, I can only get a stacktrace like this:
 
```
Error: test
    at c
```

Now I know this is a restriction of node itself. It seems to be not solvable. Just wonder if you have any thoughts about this?

**Comment by chrisveness** [comment]
I'm afraid I don't know of any way around that.

**Comment by mysyljr** [comment]
Thank you thank you. I will find another way.
